sudo: false

notifications:
  email:
    on_success: never

branches:
  only: master

cache:
  apt: true
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

matrix:
  allow_failures:
  - os: windows
  include:
  - language: ruby
    env:
    - JEKYLL_ENV=production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    addons:
      apt:
        packages: libcurl4-openssl-dev
    rvm: 2.4.1
    script:
    - bundle exec jekyll build --source ./docs/ --trace
    # https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis
    - bundle exec htmlproofer ./_site
      --check-external-hash
      --check-opengraph
      --check-sri
      --check-html
      --check-img-http
      --enforce-https
      --timeframe 4w
    after_success:
    - find ./_site -type f
  - language: minimal
    os: linux
    dist: xenial
    addons:
      apt:
        update: true
        packages: nsis
    install: true
    script:
    - echo "Hello world\n"
  - language: minimal
    os: windows
    script:
    - pwsh -Argument 'Write-Host "Hello, World!"'
